In [15]:
import numpy as np
import scipy.linalg
np.set_printoptions(precision=2)

A = np.array([
    [1, 2, -7, -19],
    [-2, -5, 16, 44],
    [7, 16, -52, -142],
    [30, 69, -225, -616]
], dtype=float)

b1 = np.array([29.01, 9.02, 33.99, -9.97], dtype=float)
b2 = np.array([29, 9, 34, -10], dtype=float)

p1 = A@b1
p2 = A@b2

f_rel = np.linalg.norm(p1-p2, np.inf) / np.linalg.norm(p1, np.inf)
print(f_rel)


1.073800738007384


In [18]:
def back_substitution(U, y):
    n = U.shape[1]
    x = np.zeros_like(y, dtype=np.double)
    x[-1] = y[-1] / U[-1, -1]
    for i in range(n - 2, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i:], x[i:])) / U[i, i]

    return x

def linsolve_qr(A, b):
    num_param = A.shape[1]
    q, r = scipy.linalg.qr(A) # Q*R*p = y
    return back_substitution(r[0:num_param], (q.T @ b)[0:num_param]) # solve for: R*p = Q.T * y


A = np.array([
    [np.sin(2*1), np.log(1**2), 1/2],
    [np.sin(2*1.5), np.log(1.5**2), 1/2],
    [np.sin(2*2), np.log(2**2), 1/2],
    [np.sin(2*2.5), np.log(2.5**2), 1/2],
])
print(A)

b = np.array([3.7, 3, 1.5, 1.8])
print(b)

q, r = scipy.linalg.qr(A)
print(q)
print(r)

p = linsolve_qr(A, b)
print(p)

error = A@p - b
print(error)

resid = np.sum(error**2)
print(resid)

[[ 0.91  0.    0.5 ]
 [ 0.14  0.81  0.5 ]
 [-0.76  1.39  0.5 ]
 [-0.96  1.83  0.5 ]]
[3.7 3.  1.5 1.8]
[[-0.59 -0.62 -0.23  0.46]
 [-0.09 -0.58  0.33 -0.74]
 [ 0.49 -0.31 -0.8  -0.17]
 [ 0.63 -0.43  0.46  0.46]]
[[-1.53  1.76  0.22]
 [ 0.   -1.69 -0.97]
 [ 0.    0.   -0.12]
 [ 0.    0.    0.  ]]
[2.95 1.97 2.01]
[-0.01  0.02  0.   -0.01]
0.0007063317893711184
