In [70]:
import numpy as np
import matplotlib.pyplot as plt

In [71]:
x = np.array([5000, 6000]) / 6000 # scaling x axis
y = np.array([100, 110])

A = np.vstack((np.ones_like(x), x)).T

p = np.linalg.solve(A, y) # Solve: A*p = y for p
cond = np.linalg.cond(A, 2) # Calculate condition

print(p)
print(cond)

[50. 60.]
22.121461697226263


In [72]:
H = np.array([[1, 1/2, 1/3],
              [1/2, 1/3, 1/4],
              [1/3, 1/4, 1/5]])

print(np.linalg.inv(H) / 9)
print(np.linalg.cond(H, 2))

[[  1.          -4.           3.33333333]
 [ -4.          21.33333333 -20.        ]
 [  3.33333333 -20.          20.        ]]
524.0567775860644


In [73]:
H = np.array([[1, 0.5, 0.33],
              [0.5, 0.33, 0.25],
              [0.33, 0.25, 0.2]])

print(np.linalg.inv(H) / 55.555555555)

[[  1.          -5.           4.6       ]
 [ -5.          26.02857143 -24.28571429]
 [  4.6        -24.28571429  22.85714286]]
