In [54]:
import numpy as np
import matplotlib.pyplot as plt

i = np.array([np.arange(1, 11, 1)])
j = np.array([np.arange(1, 11, 1)])

A = i.T@i
b = i*i

print(A@b.T)

print(np.diag(A))
print(np.diag(b))

# change diagonal values
indices = np.diag_indices_from(A)
A[indices] = [np.arange(1, 11, 1)]
print(A)

[[ 3025]
 [ 6050]
 [ 9075]
 [12100]
 [15125]
 [18150]
 [21175]
 [24200]
 [27225]
 [30250]]
[  1   4   9  16  25  36  49  64  81 100]
[1]
[[ 1  2  3  4  5  6  7  8  9 10]
 [ 2  2  6  8 10 12 14 16 18 20]
 [ 3  6  3 12 15 18 21 24 27 30]
 [ 4  8 12  4 20 24 28 32 36 40]
 [ 5 10 15 20  5 30 35 40 45 50]
 [ 6 12 18 24 30  6 42 48 54 60]
 [ 7 14 21 28 35 42  7 56 63 70]
 [ 8 16 24 32 40 48 56  8 72 80]
 [ 9 18 27 36 45 54 63 72  9 90]
 [10 20 30 40 50 60 70 80 90 10]]
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))
