In [14]:
import numpy as np
import scipy.linalg

def linsolve_cholesky(A, b):
    L = np.linalg.cholesky(A.T @ A)
    print(L)
    x = scipy.linalg.solve_triangular(L, A.T @ b, lower=True)
    return scipy.linalg.solve_triangular(L.T, x, lower=False)


A = np.array([
    [1, -3, -3**2, np.sin(np.pi * -3)],
    [1, -2.12, -2.12**2, np.sin(np.pi * -2.12)],
    [1, -0.8, -0.8**2, np.sin(np.pi * -0.8)],
    [1, -0.2, -0.2**2, np.sin(np.pi * -0.2)],
    [1, 1.11, 1.11**2, np.sin(np.pi * 1.11)],
    [1, 2.0, 2**2, np.sin(np.pi * 2)],
])
y = np.array([41.7, 21.9, 4.30, 1.13, 4.71, 15.3], dtype=np.float64)
y_one = y


p = linsolve_cholesky(A, y)
p_one = p
a, b, c, d = p
print((a, b, c, d))

print(y)
print((A @ p))
resid = np.sum(np.power((A @ p) - y, 2))
print(resid)

[[ 2.44948974  0.          0.          0.        ]
 [-1.22882735  4.23042354  0.          0.        ]
 [-3.65067869  9.91146744  2.75032001  0.        ]
 [-0.76850004  0.01131242 -0.46570416  0.36556999]]
(26.412631195719467, -6.306609918842886, 0.38177224074209215, 45.15685930760965)
[41.7  21.9   4.3   1.13  4.71 15.3 ]
[41.89651079 21.44345843  4.67104896  1.11614635  4.58633516 15.32650032]
0.4009112042168968


In [15]:
def back_substitution(U, y):
    n = U.shape[1]
    x = np.zeros_like(y, dtype=np.double)
    x[-1] = y[-1] / U[-1, -1]
    for i in range(n - 2, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i:], x[i:])) / U[i, i]

    return x

def linsolve_qr(A, b):
    num_param = A.shape[1]
    q, r = scipy.linalg.qr(A) # Q*R*p = y
    print(q)
    return back_substitution(r[0:num_param], (q.T @ b)[0:num_param]) # solve for: R*p = Q.T * y


A = np.array([
    [1, -3, -3**2, np.sin(np.pi * -3)],
    [1, -2.12, -2.12**2, np.sin(np.pi * -2.12)],
    [1, -0.8, -0.8**2, np.sin(np.pi * -0.8)],
    [1, -0.2, -0.2**2, np.sin(np.pi * -0.2)],
    [1, 1.11, 1.11**2, np.sin(np.pi * 1.11)],
    [1, 2.0, 2**2, np.sin(np.pi * 2)],
])
y = np.array([41.6, 22, 4.28, 1.12, 4.66, 15.3], dtype=np.float64)
y_two = y

p = linsolve_qr(A, y)
p_two = p
a, b, c, d = p
print((a, b, c, d))

print(y)
print((A @ p))
resid = np.sum(np.power((A @ p) - y, 2))
print(resid)

[[-0.40824829 -0.59056341  0.60220872  0.1093318  -0.25792937 -0.2084031 ]
 [-0.40824829 -0.38254641 -0.28635926  0.22786472  0.52235944  0.52934699]
 [-0.40824829 -0.07052091 -0.56333411 -0.02982089  0.0551038  -0.71210189]
 [-0.40824829  0.07130886 -0.27037142 -0.40741858 -0.65039555  0.40760692]
 [-0.40824829  0.38097052  0.38304401 -0.56813738  0.46528708 -0.04690344]
 [-0.40824829  0.59135135  0.13481206  0.66818033 -0.1344254   0.03045451]]
(26.455311510588434, -6.435226475792762, 0.43677546320665256, 45.279765361717104)
[41.6  22.    4.28  1.12  4.66 15.3 ]
[41.83001177 21.46635463  4.70917809  1.11010748  4.51238762 15.33196041]
0.5447853718831409


In [16]:
pdiff = np.linalg.norm(p_one-p_two, np.inf)
ydiff = np.linalg.norm(y_one-y_two, np.inf)

factor = pdiff / ydiff
print(factor)

1.286165569498738
